# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fca2fa38ee846d0393fe934a7281efa5d7a4820746f20adfdf39e748830ea7d8a47a6441832f17aad8748d9de83225e0c3202f480520b4f7b2197015fd67066f

test:
  secret_key_base: 0a2cd40a734e6456ce2c9bbe71019eca0508584c92e22177c0e60a9498f8526e1ba804f060f8fe7fc5a10733ba2f59a2016764cd503fba33da39448922855385

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
